import type { Metadata } from "next";
import '@fontsource/raleway/400.css';
import '@fontsource/raleway/700.css'; 
import "./globals.css";


export const metadata: Metadata = {
  title: "CCC NEXT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
      </body>
    </html>
  );
}
